name: api-tests
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - name: NPM inst
        run: npm ci
      - name: Run test
        run: npm run test
